[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The redirects are handled by Next.js, so we can remove these
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 