[build]
  command = "CI= npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  framework = "next"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# The redirects are handled by Next.js, so we can remove these
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 

[functions]
  node_bundler = "esbuild" 